server:
  port: 8081
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    # 如果前端请求带参 ?trace=true 则会显示 trace 字段
    include-stacktrace: on_param

spring:
  application:
    name: biz-service
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_HOST:localhost}:${ZOOKEEPER_PORT:2181}
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
      autoconfiguration:
        jackson:
          enabled: true
  profiles:
    active: @activatedProfile@
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:8080/auth/realms/${KEYCLOAK_REALM:console-app}/protocol/openid-connect/certs

management:
  endpoints:
    enabled-by-default: true

minio:
  endpoint: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}/
  username: ${MINIO_ROOT_USER:minio-root-user}
  password: ${MINIO_ROOT_PASSWORD:minio-root-password}
  bucket: ${MINIO_DEFAULT_BUCKET:tp-bucket}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: console-cli

keycloak:
  realm: ${KEYCLOAK_REALM:console-app}
  client-id: ${KEYCLOAK_CLIENT_ID:console-cli}
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:8080/auth
  admin:
    password: admin
    username: admin

app:
  datasource:
    biz:
      url: jdbc:postgresql://${MYSQL_HOST:localhost}:5432/biz
      jdbcUrl: jdbc:postgresql://${MYSQL_HOST:localhost}:5432/biz
      username: root
      password: ${MYSQL_ROOT_PASSWORD:example}
      driver-class-name: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
      liquibase:
        change-log: changelog.sql
    keycloak:
      url: jdbc:postgresql://${MYSQL_HOST:localhost}:5432/keycloak
      jdbcUrl: jdbc:postgresql://${MYSQL_HOST:localhost}:5432/keycloak
      username: root
      password: ${MYSQL_ROOT_PASSWORD:example}
      driver-class-name: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
  ddl-auto: validate
  show-sql: true