version: "3"

services:
  postgres:
    image: postgres:15-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"

  keycloak:
    image: bitnami/keycloak:20.0.2-debian-11-r7
    restart: always
    environment:
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=root
      - KEYCLOAK_DATABASE_PASSWORD=example
      - KEYCLOAK_PROXY=edge
      - KEYCLOAK_HTTP_RELATIVE_PATH=/auth
      - KEYCLOAK_PRODUCTION=true
      # 必须加 --hostname-strict-https=false，否则无法打开 admin 控制台
      # 参考文献 https://www.keycloak.org/server/hostname
      - KEYCLOAK_EXTRA_ARGS=--http-enabled=true --hostname-strict=false --hostname-strict-https=false
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  nginx:
    image: nginx:1.23.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - "80:80"
    extra_hosts:
      - host.docker.internal:host-gateway
