version: "3"

services:
  keycloak:
    image: bitnami/keycloak:20.0.2-debian-11-r6
    depends_on:
      - postgres
  postgres:
    image: bitnami/postgresql:15.1.0-debian-11-r17
  minio:
    image: bitnami/minio:2022.12.12-debian-11-r6
    depends_on:
      - kafka
  zookeeper:
    image: bitnami/zookeeper:3.8.0-debian-11-r72
  kafka:
    image: bitnami/kafka:3.3.1-debian-11-r29
    depends_on:
      - zookeeper
  nginx:
    image: bitnami/nginx:1.22.1-debian-11-r24
    depends_on:
      - keycloak